version: ‘3.3’
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db_data:/data/db
    restart: always
  nodejs:
    build:
      context: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/demo
      - PORT=3000
    ports:
      - 8000:3000
    depends_on:
      - mongodb