version: ‘3.3’
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=obo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    restart: always
  springboot:
    build:
      context: .
    ports:
      - 8005:8080
    depends_on:
      - mysql